name: Build and Deploy React App

on:
  push:
    branches: [ main, add-gh-pages ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      debug:
        description: 'Enable debug mode'
        required: false
        default: false
        type: boolean

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          persist-credentials: false   # required for cross-repo or gh-pages branch pushes :contentReference[oaicite:5]{index=5}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'        # use the Node.js version your project requires :contentReference[oaicite:6]{index=6}

      - name: Install dependencies
        run: npm ci                  # clean install for CI environments :contentReference[oaicite:7]{index=7}

      - name: Build production bundle
        run: npm run build           # assumes your package.json has a "build" script :contentReference[oaicite:8]{index=8}

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build
          CLEAN: true
